name: OCI Deployment

on:
  push:
    branches:
      - main

jobs:
  oci-deployment:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up OCI CLI
      - name: Set up OCI CLI
        uses: oracle-actions/setup-oci-cli@v1
        with:
          tenancy-ocid: ${{ secrets.OCI_CLI_TENANCY }}
          user-ocid: ${{ secrets.OCI_CLI_USER }}
          compartment-ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
          private-key: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          region: ${{ secrets.OCI_CLI_REGION }}

      # Step 3: Invoke the OCI DevOps Deployment Pipeline
      - name: Trigger OCI DevOps Deployment Pipeline
        run: |
          oci devops deployment create-deployment \
            --pipeline-id ${{ secrets.DEPLOYMENT_PIPELINE_OCID }} \
            --deployment-type STAGE \
            --display-name "GitHub Action Deployment"
